# env: 'CassieEnv-v0'
env: 'RoboschoolWalker2d-v1'
env_kwargs:
  alive_coef: 1.0
curriculum:
  levels: 10
  log_stdev: [-1, -2]
  compensate_power: True
  env_kwargs:
    power_coef: [1.2, 0.8]
add_timestep: False
render: False
store: True

decay_gamma: 0.99
gae_lambda: 0.95
use_peb: True

num_layers: 3
hidden_size: 256
net_version: 2
tanh_finish: true    # applies a tanh to the output of the action
                     # only works in net version 2+
varying_std: false
log_stdev: -1
lr: 0.0003
clip_eps: 0.2

save_dir: "./models/"
save_interval: 10
log_interval: 1

moving_average_tau: 0.5

epoch_per_iter: 10
batch_size: 128

l2_reg_w: 0.05

max_grad_norm: 1

num_steps: 1000
num_total_frames: 6000000
num_processes: 10 # TODO: multiprocessing.cpu_count() 

cuda: -1 # TODO: th.cuda.is_available()
seed: 17

mixing_ratio: 0  # how much DDPG style and how much PPO style gradient should be used
                 # mixing_ratio * L_ddpg + (1 - mixing_ratio) * L_ppo


record: False
c2d: False
rnn: False
data_parallel: False
pol_lr: 0.0003
vf_lr:  0.0005
