env: 'HopperBulletEnv-v0'
add_timestep: False
render: False
store: True

decay_gamma: 0.99
gae_lambda: 0.95
use_peb: True

num_layers: 3
hidden_size: 64
log_stdev: -2
lr: 0.0003
clip_eps: 0.2

save_dir: "./models/"
log_dir: "./logs/"
save_interval: 10
log_interval: 1

moving_average_tau: 0.5

epoch_per_iter: 10
batch_size: 128

l2_reg_w: 0.05

max_grad_norm: 1

num_steps: 900
num_total_frames: 2000000
num_processes: 10 # TODO: multiprocessing.cpu_count() 

cuda: False # TODO: th.cuda.is_available()
seed: 17

mixing_ratio: 0  # how much DDPG style and how much PPO style gradient should be used
                 # mixing_ratio * L_ddpg + (1 - mixing_ratio) * L_ppo


record: False
c2d: False
rnn: False
data_parallel: False
pol_lr: 0.0003
vf_lr:  0.0005